@startuml
'https://plantuml.com/activity-diagram-beta

start
card "Parse BeanDefinition" #tan{
    :resolve NamespaceHandler;
    note
    NamespaceHandlerResolver.resolve
    handler默认定义位置 META-INF/spring.handlers
    NamespaceHandler
    NamespaceHandlerSupport
    #ContextNamespaceHandler
    #AopNamespaceHandler
    end note
    :handler.init
    #registerBeanDefinitionParser
    #registerBeanDefinitionDecorator
    ;
    :handler.parse
    #get BeanDefinitionParser
    #BeanDefinitionParser.parse;

    :register PostProcessors BeanDefinition;
    :register BeanDefinition;
}

split
card "Parse BeanDefinition After 1" #tan{
:1;
:2;
:3;
:4;
}
split again

card "Parse BeanDefinition After" #tan{
    :getBean BeanDefinitionRegistryPostProcessor;
    :BeanDefinitionRegistryPostProcessor.postProcessBeanDefinitionRegistry;
    note
    **annotation callback**
    ConfigurationClassPostProcessor
    end note
    :getBean BeanFactoryPostProcessor;
    :BeanFactoryPostProcessor.postProcessBeanFactory;
    note
    **annotation callback**
    EventListenerMethodProcessor
    end note

    :SmartInitializingSingleton.afterSingletonsInstantiated;
    note
    **annotation callback**
    EventListenerMethodProcessor
    end note
}
endsplit

card "getSingleton" {
    :通过 ObjectFactory 返回不完整对象
    SmartInstantiationAwareBeanPostProcessor.getEarlyBeanReference
    ;
}

card "Instantiation Before" #skyblue    {
    :InstantiationAwareBeanPostProcessor.postProcessBeforeInstantiation;
    note
    **annotation callback**
    end note

}

card "Instantiation"{
split
    :SmartInstantiationAwareBeanPostProcessor.determineCandidateConstructors
    对构造函数进行拦截
    ;
    note
    **annotation callback**
    AutowiredAnnotationBeanPostProcessor
    end note
split again
    :instanceSupplier;
split again
    :FactoryMethod;

endsplit
    :实例已经构造,还未调用lifecycle相关方法、未依赖注入;
    :MergedBeanDefinitionPostProcessor.postProcessMergedBeanDefinition;
    note
    **default**
    ApplicationListenerDetector
    **annotation callback**
    AutowiredAnnotationBeanPostProcessor
    CommonAnnotationBeanPostProcessor
    解析注解并放入rbd.externallyManagedXXX字段中
    end note
    :添加一个 ObjectFactory 使用回调处理循环引用,无回调默认返回当前对象,不完整的bean对象
    被依赖对象通过 getSingleton方法调用 ObjectFactory 获得不完整bean对象
    SmartInstantiationAwareBeanPostProcessor.getEarlyBeanReference对早期引用进行拦截
    ;
    note
    if (!this.singletonObjects.containsKey(beanName)) {
        this.singletonFactories.put(beanName, singletonFactory);
        this.earlySingletonObjects.remove(beanName);
        this.registeredSingletons.add(beanName);
    }
    end note
}

card "Instantiation After" #skyblue {
    :InstantiationAwareBeanPostProcessor.postProcessAfterInstantiation;
    :InstantiationAwareBeanPostProcessor.postProcessProperties;
    note
    **annotation callback**
    AutowiredAnnotationBeanPostProcessor
    CommonAnnotationBeanPostProcessor
    end note
    :InstantiationAwareBeanPostProcessor.postProcessPropertyValues;

    note
    **annotation callback**
    AutowiredAnnotationBeanPostProcessor
    CommonAnnotationBeanPostProcessor
    end note
}


card "Initialization Before" #tan {
    :invokeAwareMethods
    #BeanNameAware
    #BeanClassLoaderAware
    #BeanFactoryAware;
    :BeanPostProcessor.postProcessBeforeInitialization;
    note
        SmartInstantiationAwareBeanPostProcessor.getEarlyBeanReference 功能相似
        **default**
        ApplicationContextAwareProcessor
        BeanPostProcessorChecker
        **annotation callback**
        ConfigurationClassPostProcessor
        CommonAnnotationBeanPostProcessor

    end note
    :applyPropertyValues;
    note
    xml方式：解析 beanDefinition时 全部处理完毕
    annotation方式：在Instantiation After阶段解析类内部的注解，并添加到tPropertyValues中
    beanDefinition.getPropertyValues()进行依赖注入
    end note

}

card "Initialization" {
    :InitializingBean.afterPropertiesSet;
    :invokeCustomInitMethod(beanName, bean, mbd);

}

card "Initialization After" #tan {
    :BeanPostProcessor.postProcessAfterInitialization;
    note
        SmartInstantiationAwareBeanPostProcessor.getEarlyBeanReference 功能相似
        **default**
        ApplicationListenerDetector
    end note
}
card "Use Before"{
split
    :registerDisposableBean;
split again
    :scope.registerDestructionCallback;
endsplit

}
:use;

card "destroy Before" #skyblue {
    :DestructionAwareBeanPostProcessor.postProcessBeforeDestruction;
    note
    **default**
    ApplicationListenerDetector
    **annotation callback**
    CommonAnnotationBeanPostProcessor
    end note
}
:"destroy";
stop

@enduml
