@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title My super title

* scan
** <context:component-scan/>
** annotation
*** @Configuration
*** @ComponentScan

* import
** @ImportResource
** <import/>
** @Import

* annotation
** @Component
*** @Configuration
**** bootstrap
***** AnnotationConfigApplicationContext
***** AnnotationConfigWebApplicationContext
**** @Bean

* conjunction
** @Configuration
** @ComponentScan
** @PropertySource
** @Import

* other
** @Value


* <context:annotation-config/>
** ConfigurationClassPostProcessor






header
My super header
endheader

center footer My super footer

legend right
  Short
  legend2222
endlegend
@endmindmap
