@startuml
'https://plantuml.com/activity-diagram-beta

|#skyblue|AbstractBeanFactory.doGetBean|
|#lightyellow|DefaultSingletonBeanRegistry.getSingleton(beanName, true)|
|23|

|1|
start
:a;
:b;

|3|
:c;

|2|
:d;

|1|
:f;

stop

@enduml
