@startuml
'https://plantuml.com/class-diagram


interface Advisor
    interface PointcutAdvisor extends Advisor
    interface InstantiationModelAwarePointcutAdvisor extends PointcutAdvisor
    interface IntroductionAdvisor extends Advisor, IntroductionInfo

    abstract class AbstractPointcutAdvisor implements PointcutAdvisor{
        + int getOrder()
    }
    abstract class AbstractGenericPointcutAdvisor extends AbstractPointcutAdvisor
    abstract class AbstractBeanFactoryPointcutAdvisor extends AbstractPointcutAdvisor

    class AspectJPointcutAdvisor implements PointcutAdvisor {
        - AbstractAspectJAdvice advice
        - final Pointcut pointcut
        + int getOrder()
    }
    note bottom of AspectJPointcutAdvisor
    aop 标签的advisor ,一个advice 一个advisor
    end note
    class DeclareParentsAdvisor implements IntroductionAdvisor{
        - Advice advice
    }
    note bottom of DeclareParentsAdvisor
    advice=DelegatePerTargetObjectIntroductionInterceptor
    end note
    class DefaultIntroductionAdvisor implements IntroductionAdvisor

    class DefaultPointcutAdvisor extends AbstractGenericPointcutAdvisor
    note bottom of DefaultPointcutAdvisor
    DefaultAdvisorAdapterRegistry.wrap 将advice包装成advisor
    MethodInterceptor 包装成 DefaultPointcutAdvisor
    end note

@enduml