@startuml
'https://plantuml.com/class-diagram

interface Ordered {
	int HIGHEST_PRECEDENCE = Integer.MIN_VALUE;
	int LOWEST_PRECEDENCE = Integer.MAX_VALUE;
	+ int getOrder()
}

'joinpoint
interface Joinpoint
interface Pointcut
interface ExpressionPointcut extends Pointcut
class ComposablePointcut implements Pointcut

interface Invocation extends Joinpoint
interface ConstructorInvocation extends Invocation
interface MethodInvocation extends Invocation
interface ProxyMethodInvocation extends MethodInvocation

'Advice
interface Advice
interface AfterAdvice
AfterAdvice -u---|> Advice

interface AfterReturningAdvice extends AfterAdvice
interface ThrowsAdvice extends AfterAdvice
interface BeforeAdvice extends Advice
interface MethodBeforeAdvice extends BeforeAdvice


interface AspectJPrecedenceInformation{
    + int getOrder()
}
abstract class AbstractAspectJAdvice implements Advice, AspectJPrecedenceInformation


class AspectJMethodBeforeAdvice extends AbstractAspectJAdvice implements MethodBeforeAdvice
class AspectJAfterAdvice extends AbstractAspectJAdvice implements MethodInterceptor, AfterAdvice
class AspectJAfterReturningAdvice extends AbstractAspectJAdvice implements AfterReturningAdvice, AfterAdvice
class AspectJAfterThrowingAdvice extends AbstractAspectJAdvice implements MethodInterceptor, AfterAdvice
class AspectJAroundAdvice extends AbstractAspectJAdvice implements MethodInterceptor

class TransactionInterceptor extends TransactionAspectSupport implements MethodInterceptor


'Interceptor
interface Interceptor extends Advice
interface ConstructorInterceptor extends Interceptor
interface MethodInterceptor extends Interceptor
interface DynamicIntroductionAdvice extends Advice





interface IntroductionInfo




'Advisor
interface Advisor
interface PointcutAdvisor extends Advisor
interface InstantiationModelAwarePointcutAdvisor extends PointcutAdvisor
interface IntroductionAdvisor extends Advisor, IntroductionInfo

abstract class AbstractPointcutAdvisor implements PointcutAdvisor{
    + int getOrder()
}
abstract class AbstractBeanFactoryPointcutAdvisor extends AbstractPointcutAdvisor

class AspectJPointcutAdvisor implements PointcutAdvisor {
    - AbstractAspectJAdvice advice
    - final Pointcut pointcut
    + int getOrder()
}
note bottom of AspectJPointcutAdvisor
aop 标签的advisor ,一个advice 一个advisor
end note
class DeclareParentsAdvisor implements IntroductionAdvisor
class DefaultIntroductionAdvisor implements IntroductionAdvisor

class BeanFactoryTransactionAttributeSourceAdvisor extends AbstractBeanFactoryPointcutAdvisor {
}
note bottom of BeanFactoryTransactionAttributeSourceAdvisor
事务的advisor
end note
abstract class AbstractAdvisorAutoProxyCreator extends AbstractAutoProxyCreator

class ProxyProcessorSupport extends ProxyConfig implements  BeanClassLoaderAware, AopInfrastructureBean {
     + int getOrder()
}
class AspectJAwareAdvisorAutoProxyCreator extends AbstractAdvisorAutoProxyCreator
'===========

abstract class AbstractAutoProxyCreator extends ProxyProcessorSupport implements SmartInstantiationAwareBeanPostProcessor

'static
card static {
    class AopContext{
        - ThreadLocal<Object> currentProxy
    }
}



class LazyInitTargetSource extends AbstractBeanFactoryBasedTargetSource
abstract class AbstractPrototypeBasedTargetSource extends AbstractBeanFactoryBasedTargetSource
class PrototypeTargetSource extends AbstractPrototypeBasedTargetSource
class SimpleBeanTargetSource extends AbstractBeanFactoryBasedTargetSource
abstract class AbstractBeanFactoryBasedTargetSource implements TargetSource
abstract class AbstractPoolingTargetSource extends AbstractPrototypeBasedTargetSource implements PoolingConfig
class CommonsPool2TargetSource extends AbstractPoolingTargetSource

interface TargetSource extends TargetClassAware
abstract class AopUtils{
	+ static boolean isAopProxy(@Nullable Object object)
	+ static boolean isJdkDynamicProxy(@Nullable Object object)
	+ static boolean isCglibProxy(@Nullable Object object)
}
interface TargetClassAware {
	+ Class<?> getTargetClass();
}
interface AopInfrastructureBean


class DefaultAopProxyFactory implements AopProxyFactory
class ScopedObject
interface Advised extends TargetClassAware
class AdvisedSupport extends ProxyConfig implements Advised
class ProxyCreatorSupport extends AdvisedSupport{
    - AopProxyFactory aopProxyFactory
}
class ProxyFactory extends ProxyCreatorSupport
note bottom of ProxyFactory
不依赖Ioc容器方式,创建proxy对象
end note

class ProxyFactoryBean extends ProxyCreatorSupport implements FactoryBean{

}
note bottom of ProxyFactoryBean
Ioc容器创建proxy对象
end note
class AspectJProxyFactory extends ProxyCreatorSupport
interface FactoryBean
note top
BeanFactory.FACTORY_BEAN_PREFIX="&"
所有注册到容器中的 factoryBean 的名字前缀
前缀+beanName获取factoryBean实例,
beanName获取factoryBean创建的实例
end note

interface TransactionalProxy extends SpringProxy
interface SpringProxy
note top
所有Spring的AOP代理对象都会实现,标记接口
可以用来检查代理对象是不是生成的
end note
AopUtils -- SpringProxy

class ProxyConfig{
	- boolean proxyTargetClass = false;
	- boolean optimize = false;
	- boolean opaque = false;
	- boolean exposeProxy = false;
	- boolean frozen = false;
	+ void copyFrom(ProxyConfig other)
}
skinparam GroupInheritance 4
class ScopedProxyFactoryBean extends ProxyConfig implements FactoryBean,AopInfrastructureBean{

}

class MethodLocatingFactoryBean implements FactoryBean
note bottom of MethodLocatingFactoryBean
返回一个方法
end note
interface AspectInstanceFactory {
     + int getOrder()
}
class SimpleBeanFactoryAwareAspectInstanceFactory implements AspectInstanceFactory








@enduml