@startuml
'https://plantuml.com/activity-diagram-beta

start

#tan: register
    InfrastructureAdvisorAutoProxyCreator 注册流程
    BeanPostProcessors
;

card InfrastructureAdvisorAutoProxyCreator #skyblue {


    fork
        fork
        :ContextNamespaceHandler;
            fork
            :ComponentScanBeanDefinitionParser
                            registerComponents;
           note
            <context:component-scan annotation-config="true" />
            end note
            fork again
            :AnnotationConfigBeanDefinitionParser
            parse;
            note
            <context:annotation-config>
            end note
            end fork
        fork again
        :spring boot 相关需要继续往上看
        :AnnotationConfigUtils
            registerAnnotationConfigProcessors
        ;
        end fork;



    #pink:ConfigurationClassPostProcessor
        postProcessBeanDefinitionRegistry;
    :ConfigurationClassBeanDefinitionReader
        loadBeanDefinitionsFromRegistrars;
    :AutoProxyRegistrar
        registerBeanDefinitions;


    fork again
    :AopAutoConfiguration.
        ClassProxyingConfiguration;
    :ClassProxyingConfiguration
        forceAutoProxyCreatorToUseClassProxying;
    fork again
        fork
            :CacheNamespaceHandler;
            note
            <cache:annotation-driven  />
            end note
            :AnnotationDrivenCacheBeanDefinitionParser
                registerCacheAdvisor
            ;
            fork again
            :TxNamespaceHandler;
            note
            <tx:annotation-driven  />
            end note
            :AnnotationDrivenBeanDefinitionParser
                configureAutoProxyCreator
            ;
            fork again
            :MvcNamespaceHandler
                init;
            note
            <mvc:annotation-driven  />
            end note
            :AnnotationDrivenBeanDefinitionParser
                configureAutoProxyCreator
            ;
        end fork

    :AopNamespaceUtils
        registerAutoProxyCreatorIfNecessary
    ;

    end fork
    :AopConfigUtils.registerAutoProxyCreatorIfNecessary;

}


end

@enduml
