@startuml
'https://plantuml.com/sequence-diagram

autonumber

BeanFactory -> ReferenceBean ++ : getObject()

ReferenceBean -> ReferenceBean ++ : createLazyProxy()
    ReferenceBean -> ProxyFactory: new
    ProxyFactory --> ReferenceBean: return instance
    ReferenceBean -> ProxyFactory : setTargetSource \n <color:red>DubboReferenceLazyInitTargetSource
    ReferenceBean -> ProxyFactory : 设置接口及其他数据
        ReferenceBean -> ProxyFactory ++ : getProxy
            ProxyFactory -> ProxyFactory ++ : createAopProxy()
                ProxyFactory -> ProxyFactory ++ : getAopProxyFactory()
                    ProxyFactory -> DefaultAopProxyFactory : createAopProxy(this)
                    DefaultAopProxyFactory -> JdkDynamicAopProxy : new
                    JdkDynamicAopProxy --> ProxyFactory  : return instance
                    deactivate

                ProxyFactory -> JdkDynamicAopProxy : getProxy
                JdkDynamicAopProxy -> Proxy : newProxyInstance
                note right
                JdkDynamicAopProxy 实现了InvocationHandler
                end note

            Proxy -> ProxyFactory : return proxyInstance
            deactivate
        ProxyFactory --> ReferenceBean : return proxyInstance
        deactivate
ReferenceBean --> BeanFactory : return proxyInstance
deactivate



@enduml