@startuml

(*) --> refresh()
partition refresh() {
    -d-> prepareRefresh
    -d-> obtainFreshBeanFactory
    note right
    构造beanFactory
    解析、注册 BeanDefinition
       1.用户Bean
       2.SpringBean
         BeanPostProcessor
         BeanFactoryPostProcessor
         BeanDefinitionRegistryPostProcessor
    end note
    -d-> prepareBeanFactory
    note right
    添加xml autowire模式下,不注入的依赖接口
    添加
    注册手动注册单例
    end note
    -d-> postProcessBeanFactory(beanFactory)
    -d-> invokeBeanFactoryPostProcessors(beanFactory)
    note right
    调用
    BeanDefinitionRegistryPostProcessor
        postProcessBeanDefinitionRegistry
    BeanFactoryPostProcessor
        postProcessBeanFactory

    end note
    -d-> registerBeanPostProcessors(beanFactory);
    -d-> initMessageSource();
    -d-> initApplicationEventMulticaster();
    -d-> onRefresh();
    -d-> registerListeners();
    -d-> finishBeanFactoryInitialization(beanFactory)
    -d-> finishRefresh();
}

@enduml
