@startuml
'https://plantuml.com/sequence-diagram


abstract class AbstractApplicationContext{
    -Set<ApplicationListener<?>> earlyApplicationListeners
    -Set<ApplicationListener<?>> applicationListeners
    -Set<ApplicationEvent> earlyApplicationEvents
}


@enduml

@startuml


abstract class b{
    -Set<ApplicationListener<?>> earlyApplicationListeners
    -Set<ApplicationListener<?>> applicationListeners
    -Set<ApplicationEvent> earlyApplicationEvents
}


@enduml
@startuml
start



@enduml
@startuml
(*) -->"Instantiation Before"
    -->Instantiation #pink
    -->Instantiation After
"Instantiation Before" -r-> 2
@enduml


@startuml
start
!$shared = SHARED
!$nonShared = NON-SHARED

:Minimum Reproducible Example;
if (Test Question) then (yes)
  label sp_lab0
  label lab
  else
  label sp_lab3
  label lab3
  goto sp_lab0
endif
    if (Second Test Question) then (yes)
        label sp_lab21
        label lab
    else
    :$nonShared;
    stop
    endif
label sp_lab21
:$shared;

:2;
@enduml


@startuml
' Split into 4 pages
!define PAGE_SETTING newpage

header SayHello
footer Page %page% of %lastpage%

Bob -> Alice : hello

PAGE_SETTING

Bob -> Mark : Hi
PAGE_SETTING

PAGE_SETTING



@enduml


@startuml
hide circle
hide members

package " Some Foo Package " as P1 {
    class "Foo Core" as FooCore
    class "Foo Shell" as FooShell
    class "Foo Config" as FooConfig

    FooConfig-d[hidden]-FooShell
    FooShell-d[hidden]-FooCore
}



package " Some Bar Package " as P2 {
    class "Bar Core" as BarCore
    class "Bar Shell" as BarShell
    class "Bar Config" as BarConfig
}

package " www.example.local config " as P3 {
    class " Config 1 " as Config11
    class " Config 2 " as Config12
}

package " www.example2.local config " as P4 {
    class " Config 1 " as Config21
    class " Config 2 " as Config22
}

P1 --> BarCore: creates
P2 --> Config11: creates
P2 --> Config21: creates
@enduml