
@startuml
title BeanDefinition 类结构

'子类
namespace groupChildren{
    abstract class AbstractBeanDefinition
    class GenericBeanDefinition
    note bottom of GenericBeanDefinition
    xml定义的bean
    end note
    class AnnotatedGenericBeanDefinition extends GenericBeanDefinition implements AnnotatedBeanDefinition
    class ConfigurationClassBeanDefinition extends RootBeanDefinition implements AnnotatedBeanDefinition
    class ClassDerivedBeanDefinition extends RootBeanDefinition
    class ChildBeanDefinition extends AbstractBeanDefinition
    class ScannedGenericBeanDefinition extends GenericBeanDefinition implements AnnotatedBeanDefinition
    note bottom of ScannedGenericBeanDefinition
    @Component 定义的Bean
    end note

    class BasePackagesBeanDefinition extends GenericBeanDefinition
    class EntityScanPackagesBeanDefinition extends GenericBeanDefinition
    class ServletComponentRegisteringPostProcessorBeanDefinition extends GenericBeanDefinition
    class GenericBeanDefinition extends AbstractBeanDefinition
    note bottom of GenericBeanDefinition
    xml 定义的Bean
    end note
}
class BeanDefinitionHolder implements BeanMetadataElement{
    - BeanDefinition beanDefinition
    - String beanName
    - String[] aliases
}

interface AnnotatedBeanDefinition extends BeanDefinition
class RootBeanDefinition {
    - Object beanClass
    - BeanDefinitionHolder decoratedDefinition
    - Set<Member> externallyManagedConfigMembers
    - Set<String> externallyManagedInitMethods
    - Set<String> externallyManagedDestroyMethods
}
note top of RootBeanDefinition
@PostConstruct解析后会被添加到 externallyManagedInitMethods
@PreDestroy解析后会被添加到 externallyManagedDestroyMethods
@Resource解析后,会被添加到 externallyManagedConfigMembers
end note
RootBeanDefinition ---|> AbstractBeanDefinition


interface BeanDefinition{
    + MutablePropertyValues getPropertyValues()
}

abstract class AbstractBeanDefinition extends BeanMetadataAttributeAccessor implements BeanDefinition{
    - MutablePropertyValues propertyValues
}
AbstractBeanDefinition::MutablePropertyValues ---> MutablePropertyValues




interface BeanReference extends BeanMetadataElement
class RuntimeBeanNameReference implements BeanReference
class RuntimeBeanReference implements BeanReference

interface AttributeAccessor
abstract class AttributeAccessorSupport implements AttributeAccessor
class BeanMetadataAttributeAccessor extends AttributeAccessorSupport implements BeanMetadataElement
class PropertyValue extends BeanMetadataAttributeAccessor{
	- String name
	- Object value
}
class MutablePropertyValues implements PropertyValues{
    - List<PropertyValue> propertyValueList
    - Set<String> processedProperties
    - boolean converted
}
MutablePropertyValues::propertyValueList --> PropertyValue
interface PropertyValues
interface  Iterable << PropertyValue >>
PropertyValues -u-|> Iterable

@enduml