@startuml
'https://plantuml.com/activity-diagram-beta

floating note
**spring.factories**
配置了各种spring需要的组件
spring-boot
#LoggingSystemFactory 日志组件
#PropertySourceLoader

----
**getSpringFactoriesInstances**
从文件中获取配置的组件
end note

start



card new_springApplication #SlateGray {

    :WebApplicationType.deduceFromClasspath();

    :getSpringFactoriesInstances(BootstrapRegistryInitializer.class));

    :getSpringFactoriesInstances(ApplicationContextInitializer.class);

    :getSpringFactoriesInstances(ApplicationListener.class));
    note
    向SpringApplication注册ApplicationListener
    end note

    :deduceMainApplicationClass();
}


card run_springApplication #tan {
    card createBootstrapContext #skyblue{
        #GoldenRod:new DefaultBootstrapContext();
        note
        内部有一个独立的事件广播器SimpleApplicationEventMulticaster
        end note
        #GoldenRod:this.bootstrapRegistryInitializers.initialize;
        note
        往BootstrapRegistry中注册一些需要使用的bean的supplier
        注册CloseListener
        end note
    }

    :configureHeadlessProperty();

    :SpringApplicationRunListeners listeners = getRunListeners(args);
    note
    # 获取配置的SpringApplicationRunListener组件
    # SpringApplicationRunListener包装成SpringApplicationRunListeners
    # 向SpringApplicationRunListeners注册SpringApplication中的ApplicationListener
    # **每个SpringApplicationRunListener内部都有一个独立的事件广播器 SimpleApplicationEventMulticaster**
    SpringApplicationRunListener 实现类 EventPublishingRunListener
    ----
    runListeners 向ApplicationListener发布事件
    SpringApplicationRunListeners ->  SpringApplicationRunListener -> SimpleApplicationEventMulticaster

    end note

    #pink:listeners.starting(bootstrapContext,mainApplicationClass);
    note right
    ApplicationStartingEvent
    ====
    LoggingApplicationListener
    初始化日志系统
    end note

    card createBootstrapContext #skyblue{
        :getOrCreateEnvironment();
        :configureEnvironment;
        #pink:runListeners.environmentPrepared;
        note right
        ApplicationEnvironmentPreparedEvent
        ====
        end note
        :bindToSpringApplication(environment);
    }

    :configureIgnoreBeanInfo(environment);

    #GoldenRod:createApplicationContext();

    card prepareContext #skyblue{
        :context.setEnvironment(environment);
        :postProcessApplicationContext(context);
        :applyInitializers(context);
        note
        调用ApplicationContextInitializer初始化
        ConfigurableApplicationContext
        end note

        #pink:runListeners.contextPrepared(context);
        note right
        ApplicationContextInitializedEvent
        ====
        123
        end note

        #GoldenRod:bootstrapContext.close(context);
        note right
        applicationContext已经准备好了,可以进行bean注册了
        将bootstrapContext.supplier中的bean注册到applicationContext中
        BootstrapContextClosedEvent
        ====
        **ApplicationEventMulticaster**:DefaultBootstrapContext.events
        end note

        :
         context.addBeanFactoryPostProcessor(new LazyInitializationBeanFactoryPostProcessor())
        ;
        card load #gray {
            :new BeanDefinitionLoader(registry, sources);
            :loader.load();
            note
            处理sources和primarySources
            primarySources,即run方法的参数
            sources什么时候有值?
            end note            
        }
        #pink:runListeners.contextLoaded(context);
    }
    #GoldenRod:refreshContext(context);
    #pink:runListeners.started(context, timeTakenToStartup);
    :callRunners(context, applicationArguments);
    note
    调用以下2个runner,并且前面的优先调用
    ApplicationRunner.class
    CommandLineRunner.class
    end note
    #pink:runListeners.ready(context, timeTakenToReady);
}











stop

@enduml
