@startuml
'https://plantuml.com/class-diagram

class InjectionMetadata{
    - Class<?> targetClass;
    - Collection<InjectedElement> injectedElements;
    - Set<InjectedElement> checkedElements;
    + void inject(Object target, @Nullable String beanName, @Nullable PropertyValues pvs)
}
abstract class InjectedElement{
    - Member member;
    - boolean isField;
    - PropertyDescriptor pd;
    - Boolean skip;
    # void inject(Object target, @Nullable String requestingBeanName, @Nullable PropertyValues pvs)

}
class AutowiredFieldElement extends InjectedElement{
}
class AutowiredMethodElement extends InjectedElement

@enduml