@startuml
'https://plantuml.com/activity-diagram-beta

namespace springPosts{
    interface BeanFactoryPostProcessor


    interface BeanPostProcessor
    interface MergedBeanDefinitionPostProcessor
    MergedBeanDefinitionPostProcessor -r-|> BeanPostProcessor

    interface InstantiationAwareBeanPostProcessor
    InstantiationAwareBeanPostProcessor -u-|> BeanPostProcessor
    interface SmartInstantiationAwareBeanPostProcessor
    SmartInstantiationAwareBeanPostProcessor -u-|> InstantiationAwareBeanPostProcessor

    abstract class InstantiationAwareBeanPostProcessorAdapter
    InstantiationAwareBeanPostProcessorAdapter .u.|> SmartInstantiationAwareBeanPostProcessor

    abstract class AbstractAnnotationBeanPostProcessor
    AbstractAnnotationBeanPostProcessor -u--|> InstantiationAwareBeanPostProcessorAdapter
    AbstractAnnotationBeanPostProcessor .u..|>  MergedBeanDefinitionPostProcessor

    interface BeanDefinitionRegistryPostProcessor
    BeanDefinitionRegistryPostProcessor -r--|> BeanFactoryPostProcessor
    AbstractAnnotationBeanPostProcessor --r[hidden]- BeanFactoryPostProcessor

}

namespace dubboContext {
    interface ExtensionAccessor
    class ExtensionDirector implements ExtensionAccessor
    abstract class ScopeModel implements ExtensionAccessor

    class FrameworkModel extends ScopeModel
    class ApplicationModel extends ScopeModel


    interface ScopeModelAccessor
    interface ExtensionPostProcessor
    class ScopeModelAwareExtensionProcessor implements ExtensionPostProcessor, ScopeModelAccessor


    class ScopeBeanFactory

    class FrameworkServiceRepository
    class ExtensionLoader<T>
    class DubboSpringInitContext

}


' dubboService @dubboService
namespace dubboService {
    abstract class AbstractConfig
    abstract class AbstractMethodConfig extends AbstractConfig
    abstract class AbstractInterfaceConfig extends AbstractMethodConfig
    abstract class AbstractServiceConfig extends AbstractInterfaceConfig
    abstract class ServiceConfigBase<T> extends AbstractServiceConfig
    class ServiceConfig<T> extends ServiceConfigBase
    class ServiceBean<T> extends ServiceConfig
    note right of ServiceBean
    @DubboService 注解beanDefinition的beanClass
    end note
}


' dubboReference @DubboReference
namespace dubboReference {
    interface FactoryBean<T>
    class ReferenceBean<T> {
        - ReferenceConfig referenceConfig
        + void afterPropertiesSet()
        - void createLazyProxy()
    }
    ReferenceBean -d--> FactoryBean
    note right of ReferenceBean
    ReferenceBean实例创建后,设置proxy创建需要的信息,并将实例保存到ReferenceBeanManager中
    ReferenceBean#afterPropertiesSet
    ===
    使用代理方式创建provider接口的子类
    ReferenceBean#createLazyProxy
    ===
    referenceConfig实际逻辑的封装
    ===
    # ReferenceBean#createLazyProxy 使用spring封装的jdk动态代理创建代理对象,并不实际创建dubbo代理对象
    # 调用spring封装的JdkDynamicAopProxy#invoke时,即接口方法调用时,触发获取dubbo代理对象
    # DubboReferenceLazyInitTargetSource#createObject创建dubbo内部的代理对象
    # dubbo内部拦截器InvokerInvocationHandler#invoke调用远程的服务化方法
    end note

    interface ProviderInterface
    interface EchoService
    interface Destroyable
    class ReferenceBeanProxy
    ProviderInterface <|... ReferenceBeanProxy
    EchoService <|... ReferenceBeanProxy
    Destroyable <|... ReferenceBeanProxy

    interface TargetSource
    abstract class AbstractLazyCreationTargetSource
    class DubboReferenceLazyInitTargetSource {
        + Object createObject()
    }
    TargetSource <|... AbstractLazyCreationTargetSource
    AbstractLazyCreationTargetSource <|--- DubboReferenceLazyInitTargetSource



    class JdkDynamicAopProxy implements  InvocationHandler

    ReferenceBeanProxy --> JdkDynamicAopProxy : 1.调用invoke
    JdkDynamicAopProxy --> DubboReferenceLazyInitTargetSource : 2.创建或返回代理对象
    ReferenceBean <-u- DubboReferenceLazyInitTargetSource : 3 referenceConfig.get() 创建doubbo代理对象


}




' dubboPosts
namespace dubboPosts{

    class ReferenceAnnotationBeanPostProcessor {
        + void postProcessBeanFactory
        + void postProcessMergedBeanDefinition
        ===
        + void postProcessMergedBeanDefinition
        + PropertyValues postProcessPropertyValues
        --
        - ConcurrentMap<InjectionMetadata.InjectedElement, String> injectedFieldReferenceBeanCache
        - ConcurrentMap<InjectionMetadata.InjectedElement, String> injectedMethodReferenceBeanCache
    }
    ReferenceAnnotationBeanPostProcessor -u--|> springPosts.AbstractAnnotationBeanPostProcessor
    ReferenceAnnotationBeanPostProcessor .u...|> springPosts.BeanFactoryPostProcessor


    class DubboInfraBeanRegisterPostProcessor
    DubboInfraBeanRegisterPostProcessor .d....|> springPosts.BeanDefinitionRegistryPostProcessor

    class ServiceAnnotationPostProcessor
    ServiceAnnotationPostProcessor ...|> springPosts.BeanDefinitionRegistryPostProcessor

    DubboInfraBeanRegisterPostProcessor -l[hidden]-- ServiceAnnotationPostProcessor

}


' dubboServiceAnnotation note
note as dubboServiceAnnotation
    postProcessBeanDefinitionRegistry
end note

dubboPosts.ServiceAnnotationPostProcessor -l-> dubboServiceAnnotation
dubboService.ServiceBean ---> dubboServiceAnnotation


' dubboReferenceAnnotation note
note as dubboReferenceAnnotation
== beanDefinition 解析阶段 ==
**postProcessBeanFactory**

== bean 创建阶段 ==
**postProcessMergedBeanDefinition**

end note

dubboPosts.ReferenceAnnotationBeanPostProcessor -d--- dubboReferenceAnnotation
dubboReferenceAnnotation  ---- dubboReference.ReferenceBean : @DubboReference的FactoryBean

' regstart
namespace dubboRegistrar{
    class DubboConfigConfigurationRegistrar implements ImportBeanDefinitionRegistrar
}



namespace dubboRegsterBeanDefinitions{
   class DubboSpringInitContext
   class ApplicationModel
   class ModuleModel
   class ServicePackagesHolder
   class ReferenceBeanManager
   class DubboConfigAliasPostProcessor
   class DubboDeployApplicationListener
   class DubboConfigApplicationListener
   class DubboConfigDefaultPropertyValueBeanPostProcessor
   class DubboConfigBeanInitializer

   DubboSpringInitContext -d[hidden]- ApplicationModel
   ApplicationModel -d[hidden]- ModuleModel
   ModuleModel -d[hidden]- ServicePackagesHolder
   ServicePackagesHolder -d[hidden]- ReferenceBeanManager
   ReferenceBeanManager -d[hidden]- DubboConfigAliasPostProcessor
   DubboConfigAliasPostProcessor -d[hidden]- DubboDeployApplicationListener
   DubboDeployApplicationListener -d[hidden]- DubboConfigApplicationListener
   DubboConfigApplicationListener -d[hidden]- DubboConfigDefaultPropertyValueBeanPostProcessor
   DubboConfigDefaultPropertyValueBeanPostProcessor -d[hidden]- DubboConfigBeanInitializer
}

circle dubboRegistrarLink
dubboRegistrar.DubboConfigConfigurationRegistrar --- dubboRegistrarLink : register
dubboRegistrarLink -[#blue]-- dubboPosts
dubboRegistrarLink -[#blue]---- dubboRegsterBeanDefinitions

@enduml
