@startuml
'https://plantuml.com/activity-diagram-beta

start
    :DubboApplicationContextInitializer;
    note
    已注释掉
    end note

    :DubboDefaultPropertiesEnvironmentPostProcessor;

    :EnableAutoConfiguration;

fork
    :DubboAutoConfiguration;
    :@Bean
    ServiceAnnotationPostProcessor;

    :@EnableDubboConfig
    @Import(DubboConfigConfigurationRegistrar.class)
    ;
    :DubboConfigConfigurationRegistrar#registerBeanDefinitions;
    note
    注册的beanDefinition
    == **dubbo bean** ==
    **DefaultListableBeanFactory#manualSingletonNames**
    # DubboSpringInitContext
    # ApplicationModel
    # ModuleModel
    ====
    # ServicePackagesHolder
    # ReferenceBeanManager
    == ** spring bean ** ==
    -- post --
    # ReferenceAnnotationBeanPostProcessor
    # DubboConfigAliasPostProcessor
    # DubboConfigDefaultPropertyValueBeanPostProcessor
    # DubboInfraBeanRegisterPostProcessor
    -- listener --
    # DubboDeployApplicationListener
    # DubboConfigApplicationListener
    -- InitializingBean --
    # DubboConfigBeanInitializer

    end note


fork again
    :DubboRelaxedBindingAutoConfiguration;
fork again
    :DubboListenerAutoConfiguration;

end fork



stop

@enduml
