@startuml
'https://plantuml.com/activity-diagram-beta

start
: initializeFrameworkModel(FrameworkModel frameworkModel);
note
--ClusterScopeModelInitializer--
**registerBean**
RouterSnapshotSwitcher

--CommonScopeModelInitializer--
**registerBean**
FrameworkExecutorRepository
ConverterUtil

--ConfigScopeModelInitializer--
**addDestroyListener**
FrameworkModelCleaner

--MetadataScopeModelInitializer--
none

--QosScopeModelInitializer--
**registerBean**
Server

--RegistryScopeModelInitializer--
none

--RemotingScopeModelInitializer--
none

--SpringScopeModelInitializer--
none

end note

:initializeApplicationModel(ApplicationModel applicationModel);
note
--ClusterScopeModelInitializer--
**registerBean**
MergerFactory
ClusterUtils

--CommonScopeModelInitializer--
**registerBean**
ShutdownHookCallbacks
FrameworkStatusReportService
ConfigurationCache

--ConfigScopeModelInitializer--
**registerBean**
DefaultConfigValidator
DefaultApplicationDeployer
applicationModel.setDeployer(applicationDeployer)

--MetadataScopeModelInitializer--
**registerBean**
MetadataReportInstance

--QosScopeModelInitializer--
none

--RegistryScopeModelInitializer--
**registerBean**
RegistryManager

--RemotingScopeModelInitializer--
**addDestroyListener**
zk相关监听器

--SpringScopeModelInitializer--
none

end note

:initializeModuleModel(ModuleModel moduleModel);
note
--ClusterScopeModelInitializer--
**registerBean**
MeshRuleManager

--CommonScopeModelInitializer--
**registerBean**
ConfigurationCache

--ConfigScopeModelInitializer--
**registerBean**
DefaultModuleDeployer
moduleModel.setDeployer(moduleDeployer)

--MetadataScopeModelInitializer--
none

--QosScopeModelInitializer--
none

--RemotingScopeModelInitializer--
none

--SpringScopeModelInitializer--
none

end note

stop

@enduml
